language: node_js
node_js:
  - "6.2.2"
  - "5.12.0"
  - "4.4.7"
services:
- mongodb
notifications:
  email: false
before_script:
  - npm install mongoose
  - sleep 15

env:
  - NODE_ENV=development
  